import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { searchDecisionMakersFn, enrichPersonContactFn } from "@/lib/people-search.functions";
export const Route=createFileRoute("/_authenticated/decision-makers")({component:DecisionMakersPage});
const roles=["Other","Founder","Co-Founder","Owner","CEO","Managing Director","Director","Partner","CMO","Marketing Director","Head of Marketing","Head of Sales"];
const services=["Website Development","Website Redesign","Meta Ads","Google Ads","TikTok Ads","YouTube Ads","SEO","Social Media","Amazon PPC/FBA","Website + Ads","Other"];
function DecisionMakersPage(){const search=useServerFn(searchDecisionMakersFn),enrich=useServerFn(enrichPersonContactFn);const [query,setQuery]=useState(""),[location,setLocation]=useState(""),[role,setRole]=useState("Other"),[service,setService]=useState("Website Development"),[results,setResults]=useState<any[]>([]),[busy,setBusy]=useState(false);
async function run(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await search({data:{query,location,role,targetService:service,limit:30}});setResults(r.results);if(!r.results.length)toast.info("No verified public results found.");}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
async function enrichOne(p:any){try{const r=await enrich({data:{id:p.id,full_name:p.full_name,company_name:p.company_name,company_url:p.company_url??null,linkedin_url:p.linkedin_url??null,table:"decision_makers"}});setResults(x=>x.map(v=>v===p?{...v,...r}:v));toast.success("Contact enrichment completed.");}catch(e){toast.error((e as Error).message)}}
return <div className="space-y-4"><div><h1 className="text-lg font-semibold">Decision Makers</h1><p className="text-sm text-muted-foreground">Find founders, owners and senior decision makers — not generic company inboxes.</p></div><Card><CardHeader><CardTitle className="text-base">Find people</CardTitle></CardHeader><CardContent><form onSubmit={run} className="grid gap-3 md:grid-cols-5 md:items-end"><div className="md:col-span-2"><Label>Company / business / query</Label><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="restaurants in Lahore" required/></div><div><Label>Location</Label><Input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Lahore, Pakistan"/></div><div><Label>Role</Label><Select value={role} onValueChange={setRole}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{roles.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Target service</Label><Select value={service} onValueChange={setService}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{services.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="md:col-span-5"><Button disabled={busy} type="submit">{busy?"Researching…":"Find decision makers"}</Button></div></form></CardContent></Card><div className="space-y-3">{results.map((p,i)=><Card key={p.id??i}><CardContent className="p-4"><div className="flex items-start justify-between"><div><div className="font-medium">{p.full_name}</div><div className="text-sm text-muted-foreground">{p.job_title??"Decision maker"} · {p.company_name}</div></div><Badge variant="outline">{p.confidence}</Badge></div><div className="mt-3 grid gap-1 text-sm"><div>Location: {p.location??"Not found"}</div><div>LinkedIn: {p.linkedin_url?<a className="underline" href={p.linkedin_url} target="_blank" rel="noreferrer">Open profile</a>:"Not found"}</div><div>Professional email: {p.professional_email??"Not found"}</div><div>Professional phone: {p.professional_phone??"Not found"}</div></div><p className="mt-3 text-xs text-muted-foreground">{p.evidence}</p><Button size="sm" variant="outline" className="mt-3" onClick={()=>enrichOne(p)}>Enrich contact</Button></CardContent></Card>)}</div></div>}
