/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedOnlineSearchRouteImport } from './routes/_authenticated/online-search'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads/index'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads/$leadId'
import { Route as ApiPublicGmailCallbackRouteImport } from './routes/api/public/gmail/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnlineSearchRoute =
  AuthenticatedOnlineSearchRouteImport.update({
    id: '/online-search',
    path: '/online-search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicGmailCallbackRoute = ApiPublicGmailCallbackRouteImport.update({
  id: '/api/public/gmail/callback',
  path: '/api/public/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/import': typeof AuthenticatedImportRoute
  '/online-search': typeof AuthenticatedOnlineSearchRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/api/public/gmail/callback': typeof ApiPublicGmailCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/import': typeof AuthenticatedImportRoute
  '/online-search': typeof AuthenticatedOnlineSearchRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/api/public/gmail/callback': typeof ApiPublicGmailCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/online-search': typeof AuthenticatedOnlineSearchRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/api/public/gmail/callback': typeof ApiPublicGmailCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/import'
    | '/online-search'
    | '/outreach'
    | '/settings'
    | '/leads/$leadId'
    | '/leads/'
    | '/api/public/gmail/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/import'
    | '/online-search'
    | '/outreach'
    | '/settings'
    | '/leads/$leadId'
    | '/leads'
    | '/api/public/gmail/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/history'
    | '/_authenticated/import'
    | '/_authenticated/online-search'
    | '/_authenticated/outreach'
    | '/_authenticated/settings'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/leads/'
    | '/api/public/gmail/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGmailCallbackRoute: typeof ApiPublicGmailCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online-search': {
      id: '/_authenticated/online-search'
      path: '/online-search'
      fullPath: '/online-search'
      preLoaderRoute: typeof AuthenticatedOnlineSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/gmail/callback': {
      id: '/api/public/gmail/callback'
      path: '/api/public/gmail/callback'
      fullPath: '/api/public/gmail/callback'
      preLoaderRoute: typeof ApiPublicGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedOnlineSearchRoute: typeof AuthenticatedOnlineSearchRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedOnlineSearchRoute: AuthenticatedOnlineSearchRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGmailCallbackRoute: ApiPublicGmailCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
